spring.datasource.url=jdbc:mariadb://db2.csse.canterbury.ac.nz:3306/seng302-2025-team200-prod?sslMode=trust
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.h2.console.enabled=false
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update

app.domain = https://csse-seng302-team200.canterbury.ac.nz/prod