INSERT INTO `tag` (`tag_name`) VALUES
                                   ('Architecture'),
                                   ('Additions'),
                                   ('Asbestos'),
                                   ('Basement'),
                                   ('Blueprints'),
                                   ('Brickwork'),
                                   ('Cabinetry'),
                                   ('Construction'),
                                   ('CAD'),
                                   ('Demolition'),
                                   ('Drywall'),
                                   ('Decking'),
                                   ('Electrical'),
                                   ('Energy Efficiency'),
                                   ('Excavation'),
                                   ('Flooring'),
                                   ('Framing'),
                                   ('Fixtures'),
                                   ('Gutters'),
                                   ('Garage'),
                                   ('Grouting'),
                                   ('HVAC'),
                                   ('Hardwood'),
                                   ('Historic'),
                                   ('Insulation'),
                                   ('Interior Design'),
                                   ('Installation'),
                                   ('Joists'),
                                   ('Jackhammering'),
                                   ('Jambs'),
                                   ('Kitchen Remodel'),
                                   ('Knockdown Texture'),
                                   ('Knobs'),
                                   ('Landscaping'),
                                   ('LoadBearing'),
                                   ('Lighting'),
                                   ('Masonry'),
                                   ('Modernization'),
                                   ('Materials'),
                                   ('Nailing'),
                                   ('New Construction'),
                                   ('Noise Reduction'),
                                   ('Open Concept'),
                                   ('Overhang'),
                                   ('Outdoor Living'),
                                   ('Plumbing'),
                                   ('Paint'),
                                   ('Permits'),
                                   ('Quartz Countertops'),
                                   ('Quality Control'),
                                   ('Quick Dry'),
                                   ('Renovation'),
                                   ('Roofing'),
                                   ('Restoration'),
                                   ('Siding'),
                                   ('Skylights'),
                                   ('Subflooring'),
                                   ('Tiling'),
                                   ('Trim Work'),
                                   ('Texture'),
                                   ('Upgrades'),
                                   ('Underlayment'),
                                   ('Utility Room'),
                                   ('Vinyl Flooring'),
                                   ('Ventilation'),
                                   ('Value'),
                                   ('Windows'),
                                   ('Waterproofing'),
                                   ('Wall Removal'),
                                   ('Xeriscaping'),
                                   ('X-Bracing'),
                                   ('XPS Insulation'),
                                   ('Yard Renovation'),
                                   ('Yellow Paint'),
                                   ('Yield Improvements'),
                                   ('Zoning'),
                                   ('Z-Flashing'),
                                   ('Zero Energy');
